### ISSUE TITLE
"Show in Finder" not working?

### ISSUE THREAD

**Issue by ghost** [meeech/Shopify-Theme-Tool-Public#12]
This is the dropdown option, under the little sprocket icon. Selecting it results in nothing happening.

**Comment by meeech** [comment]
Hey Luc,

I'm not able to reproduce it. Can you give me some details re: what version OSX you using, whats the path to the folder?

**Comment by ghost** [comment]
OSX 10.6.8 and the path is inside my Documents folder, in a folder marked "shopify": /Users/luclatulippe/Documents/shopify

Otherwise, it's working great! :) This isn't a huge deal.

**Comment by meeech** [comment]
Hey luc, have you tried it with other themes - broken for all? or just this one?

**Comment by ghost** [comment]
Yep, for all of them. Tried restarting a few times, no luck.

**Comment by meeech** [comment]
DO you have console.app on your machine? Should be in Applications/Utilities/Console

If you could launch the app, and then console. Then try to Show In Finder. If there's an error, it should show up in Console.app - Something like: 04/06/12 1:59:24 AM  [0x0-0x2596594].com.meeech.shopify_theme2[35233]    ... If you could copy and paste that into a text file and  email to me, that would be helpful to try to track this down.

**Comment by ghost** [comment]
Oddly enough, nothing shows up in Console when I do that. Other actions do, but not the "show in Finder" action. Here's a before and after screencap: http://cl.ly/H7Tz  //  http://cl.ly/H7uS

Other actions -- like saving files -- do register in Console, just not that one.

**Comment by meeech** [comment]
Thanks luc. Screenshot helped. It was a path issue. fix will come with next release. Its the use of spaces in path name.
