### ISSUE TITLE
Not Syncing, Mountain Lion 10.8

### ISSUE THREAD

**Issue by khedaywi** [meeech/Shopify-Theme-Tool-Public#16]
Recently upgraded to Mountain Lion

Seems as though syncing isn't working in Mountain Lion, at least on my machine

Tried "reinstalling" the app and redownloaded the theme I was working on, but still not working. :(

**Comment by meeech** [comment]
lookking into it

**Comment by khedaywi** [comment]
Awesome. Let me know if there's anything I can do...

**Comment by svizzari** [comment]
Any progress on this issue?

**Comment by meeech** [comment]
yep. Working on the solution right now actually. shouldnt be much longer.

**Comment by svizzari** [comment]
That's great news!  Thanks for the speedy update.

**Comment by svizzari** [comment]
Sorry to bug you, but any update? ;)

**Comment by meeech** [comment]
@s-vizzari No bother. Pleased to report i have a new version for testing.  Email me (mitchell@amihod.com), and I'll send you the link.

**Comment by ghost** [comment]
Thought it was just me! I'm having this trouble with STT in ML as well. No rush, I can wait for the next version.

**Comment by meeech** [comment]
@luclatulippe have you tried the latest? http://apps.shopify.com/desktop-theme-editor

**Comment by ghost** [comment]
A-ha! No, I still had version 1.0, not 1.0.1. Thanks! I'm a late convert to Mountain Lion so I missed that. BTW: when opening this newest version, it gives this warning: "…can’t be opened because it is from an unidentified developer." I can force-open it, but is it typical of it to do that?
