### ISSUE TITLE
support for more than 13 shops

### ISSUE THREAD

**Issue by BENGMN** [meeech/Shopify-Theme-Tool-Public#17]
App allows you to add as many stores as you want, but only allows you to see the first 13 shops listed under the "Your Shops:" heading. Perhaps a scroll-bar would solve this issue.

Thanks for the awesome tool.

**Comment by meeech** [comment]
fixed in new release. Beta is now available. https://github.com/meeech/Shopify-Theme-Tool/releases/tag/v1.0.3-rc1
