### ISSUE TITLE
Freezes on theme download

### ISSUE THREAD

**Issue by Spacetrader** [meeech/Shopify-Theme-Tool-Public#4]
It starts the download and freezes.
In fact it has downloaded all the files and if you close the app and open it again it will display the theme.

**Comment by khedaywi** [comment]
I'm getting the same issue. Download freezes, but if you reopen it's fine.

**Comment by mobweb** [comment]
Same here. I'm using the Radiance theme, and the app freezes when downloading /assets/radiance.js. Looking at the files reveals that all the files have been completely downloaded, including radiance.js.

**Comment by meeech** [comment]
interesting. I'll have a look and try to see what's up.

**Comment by meeech** [comment]
same as issue #8. resolved. the fix will be in next release.
