### ISSUE TITLE
Multiple files changes not being synced

### ISSUE THREAD

**Issue by Spacetrader** [meeech/Shopify-Theme-Tool-Public#6]
If you change multiple files, i.e on Textmate, and perform a "save all" the app will not sync the changes.
To workaround you should simple hit "Force Deploy" option.

**Comment by meeech** [comment]
thanks for that. I'll have to look and see whats up. Save all should have the same effect.

**Comment by meeech** [comment]
resolved in latest release. A few savealls from TM worked. Let me know if you still have this issue.
