### ISSUE TITLE
No feedback when upload is done

### ISSUE THREAD

**Issue by mobweb** [meeech/Shopify-Theme-Tool-Public#9]
I don't know if it's planned, but I would definitely appreciate some sort of feedback when my changed file has been uploaded to the server. My connection at home is very slow and it sometimes takes over a minute to upload a large file (for example my main CSS file). Perhaps a beep sound, like Coda does it when the upload is complete?

**Comment by meeech** [comment]
I'll look at making it an option, not a default behaviour.

**Comment by shhstudios** [comment]
Yeah, a growl notification would be nice, like how it shows when the theme has finished downloading.

**Comment by meeech** [comment]
seems like that would start to get annoying (if you save frequently), but will look at adding it as an option.

**Comment by meeech** [comment]
added for next version. growl notif when upload done.
